name: Build & Deploy to Github Pages
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - uses: dtolnay/rust-toolchain@stable
    
    - name: install mdbook
      run: |
        cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
        cargo install mdbook-katex --vers "^0.9" --locked
    
    - name: Build book
      run: mdbook build

    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: book/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}